[package]
name = "blog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark = "0.9.2"
blake3 = { version = "1.3.1", git = "https://github.com/BLAKE3-team/BLAKE3" }
memmap2 = "0.5.8"
hex = "0.4.3"
chrono = { version = "0.4.23", default-features = false, features = ["clock"] }
minify-html = "0.10.7"
syntect = "5.0.0"
lazy_static = "1.4.0"

