[package]
name = "blog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
minify = []

[dependencies]
pulldown-cmark = { version = "0.9.3" }
blake3 = { version = "1.3.1", git = "https://github.com/BLAKE3-team/BLAKE3" }
chrono = { version = "0.4.30", default-features = false, features = ["clock"] }
minify-html = "0.11.1"
syntect = "5.1.0"
# latex2mathml = "0.2.3"
mini = { path = "../mini", version = "0.1.0", features = ["profile"] }
